amigos_all = {
'proposed_sites':{ 'name':'sites', 'cols':['ogc_fid', ]},
'laco_parks':{ 'name':'parks', 'cols':['ogc_fid', 'park', 'addr1', 'addr2',]},
'soils_2004':{ 'name':'soils', 'cols':[ 'ogc_fid', 'class',]},
'drp_bikeway_plan':{ 'name':'bikeways', 'cols':[ 'ogc_fid', 'namea_alf',]},
'allbillboardsbuffer':{ 'name':'bbbuffer', 'cols':[ 'ogc_fid','address',]},
'laparcelsunder3000':{ 'name':'smallparcels', 'cols':[ 'ogc_fid',]},
'drp_freeways_simple':{ 'name':'freeways', 'cols':[ 'ogc_fid', 'rte1_alf', 'type_name', ]},
'smallparcelsnearwaterways':{ 'name':'smallparcelsnearwater', 'cols':[ 'ogc_fid',]},
'foundbillboards':{ 'name':'foundbillboards', 'cols':[ 'ogc_fid',]},
'parcel':{ 'name':'parcels', 'cols':['ogc_fid','lot', 'block', 'parcel_typ', 'shape_area', 'usecode']},
'laco_libraries':{ 'name':'libraries', 'cols':[ 'ogc_fid', 'name', 'addr_', 'addr2', 'phone']},
'raillines1109':{ 'name':'raillines', 'cols':[ 'ogc_fid', 'line', 'name']},
'geocodedbillboards':{ 'name':'geocodedbillboards', 'cols':[ 'ogc_fid', 'address', 'city', 'state',]},
'landtypes_20110425':{ 'name':'landtypes', 'cols':[ 'ogc_fid', 'name', 'cat1', 'cat2', 'addrln1', ]},
'metrobusstops1210':{ 'name':'busstops', 'cols':[ 'ogc_fid', 'stopnum', 'along', 'at', ]},
'tgr06037blk00':{ 'name':'censusblocks', 'cols':[ 'ogc_fid',]},
'tgr06037lka':{ 'name':'roads', 'cols':[ 'ogc_fid',]},
'dpw_smd_nosmd_pp':{ 'name':'noncountysewers', 'cols':[ 'ogc_fid',]},
'dpw_smd_swr_pp':{ 'name':'countysewers', 'cols':[ 'ogc_fid', 'type', 'diameter', 'street', 'p_length', 'jur', 'matl']},
'rapido1210':{ 'name':'rapidmetrolines', 'cols':[ 'ogc_fid', 'var_route', 'var_ident', 'var_direc', 'var_descr',]},
'tgr06037lkh':{ 'name':'hydrography', 'cols':[ 'ogc_fid', ]},
'waterpurveyors':{ 'name':'waterpurveyors', 'cols':[ 'ogc_fid','name1', 'addr1', 'addr2', 'phone', ]},
}

amigos_test = {
'proposed_sites':{ 'name':'sites', 'cols':['ogc_fid', ]},
'geocodedbillboards':{ 'name':'geocodedbillboards', 'cols':[ 'ogc_fid', 'address', 'city', 'state',]},
'foundbillboards':{ 'name':'foundbillboards', 'cols':[ 'ogc_fid',]},
'laco_parks':{ 'name':'parks', 'cols':['ogc_fid', 'park', 'addr1', 'addr2',]},
'metrobusstops1210':{ 'name':'busstops', 'cols':[ 'ogc_fid', 'stopnum', 'along', 'at', ]},
'raillines1109':{ 'name':'raillines', 'cols':[ 'ogc_fid', 'line', 'name']},
'dpw_smd_nosmd_pp':{ 'name':'noncountysewers', 'cols':[ 'ogc_fid',]},
'dpw_smd_swr_pp':{ 'name':'countysewers', 'cols':[ 'ogc_fid', 'type', 'diameter', 'street', 'p_length', 'jur', 'matl']},
#'drp_freeways_simple':{ 'name':'freeways', 'cols':[ 'ogc_fid', 'rte1_alf', 'type_name', ]},
'laparcelsunder3000':{ 'name':'smallparcels', 'cols':[ 'ogc_fid',]},
'drp_bikeway_plan':{ 'name':'bikeways', 'cols':[ 'ogc_fid', 'namea_alf',]},
'tinnode199':{ 'name': 'terrain', 'cols':[ 'elevation', ]},
'tinnode406':{ 'name': 'terrain', 'cols':[ 'elevation', ]},
'tinnode661':{ 'name': 'terrain', 'cols':[ 'elevation', ]},
}
